### ISSUE TITLE
No reaction on coverage reports

### ISSUE THREAD

**Issue by Flamefire** [codecov/support#168]
I get ocassionally no reaction from codecov for my PRs (no Status on Github, no comment,...) For example here: https://codecov.io/gh/Return-To-The-Roots/s25client/commit/0ff93c1957294487ec9021fec7e475d31dc3b660/builds

I can see a suspicious line in the 'Builds' tab: `upload  True  error=Unknown-report`

**Comment by stevepeak** [comment]
We have had some random issues/outages over this migration week. As of now most the product is stable and we are battling only a couple issues that impact system performance but not causing issues with features.

I do notice a comment posted on this commit. 👍  I'm under the impression this is fixed, but please let me know if you find otherwise.

Thank you!

**Comment by Flamefire** [comment]
Yes we seem to get responses now, thanks. They are still wrong, but that is discussed in #164
